version: "3"

services:
  fileserver:
    image: 127.0.0.1:5000/fileserver
    build: ./fileserver
    container_name: fileserver
    volumes:
      - ./fileserver:/app
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://jackson:portable20relaydb!@db/pg_db
      - POSTGRES_HOST_URL=db
    ports:
      - 4000:4000
    logging:
      options:
        max-file: "3"
        max-size: "250m"
  db:
    image: arm32v7/postgres:latest
    environment:
      - POSTGRES_USER=jackson
      - POSTGRES_PASSWORD=portable20relaydb!
      - POSTGRES_DB=pg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-file: "3"
        max-size: "250m"
  
  adminer:
    image: adminer
    ports:
      - 8088:8081
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    depends_on: 
      - db

volumes:
  postgres_data: