version: "3"

services:
  fileserver:
    image: 127.0.0.1:5000/fileserver
    build: ./fileserver
    container_name: fileserver
    volumes:
      - ./fileserver:/app
    depends_on:
      - db
    environment:
      - MIX_ENV=prod
      - DATABASE_URL=ecto://jackson:pass1247@db/pg_db
    ports:
      - 4000:4000
    logging:
      options:
        max-file: "3"
        max-size: "250m"
  db:
    image: arm32v7/postgres:latest
    environment:
      - POSTGRES_USER=jackson
      - POSTGRES_PASSWORD=pass1247
      - POSTGRES_DB=pg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-file: "3"
        max-size: "250m"

volumes:
  postgres_data: