# WARNING: this file is not suitable for production, please use with caution
version: "3"

services:
  fileserver:
    image: 127.0.0.1:5000/fileserver
    build: ./fileserver
    container_name: fileserver
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: "ecto://jackson:123123@db/jackson_db"
      CURRENT_SERVER: local
      PORT: "4000"
      POSTGRES_HOST_URL: "db"
      POSTGRES_HOST_URL_DEFAULT: "localhost"
      ORIGIN_BASE: "localhost"
      ORIGIN_URL: "http://localhost"
      ORIGIN_PORT: "4000"
    ports:
      - 4000:4000
    logging:
      options:
        max-file: "3"
        max-size: "250m"
  db:
    image: arm32v7/postgres:latest
    environment:
      - POSTGRES_USER=jackson
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-file: "3"
        max-size: "250m"
        
volumes:
  postgres_data: