version: '3.8'

services:
  fileserver:
    image: 127.0.0.1:5000/fileserver
    command: ["mix", "phx.server"]
    volumes:
      - ./fileserver/logs:/tmp
      - ./fileserver/test:/app/test
      - ./fileserver/mix.exs:/mix.exs
      - ./fileserver/mix.lock:/app/mix.lock
      - ./fileserver/.formatter.exs:/app/.formatter.exs
      - ./fileserver/lib:/app/lib
      - ./fileserver/priv:/app/priv
      - ./fileserver/config:/app/config
      - ./fileserver/assets/css:/app/assets/css
      - ./fileserver/assets/static:/app/assets/static
      - ./fileserver/assets/js:/app/assets/js
      - ./fileserver/assets/webpack.config.js:/app/assets/webpack.config.js
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://jackson:portable20relaydb!@db/pg_db
      - POSTGRES_HOST_URL=db
    ports:
      - 4000:4000
    logging:
      options:
        max-file: "3"
        max-size: "250m"
    networks:
      - traefik-public
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        traefik.http.routers.fileserver.entrypoints: web
        traefik.http.routers.fileserver.rule: Host(`fileserver.bankjsy.giize.com`)
        traefik.http.services.fileserver.loadbalancer.server.port: 4000

  db:
    image: arm32v7/postgres:latest
    environment:
      - POSTGRES_USER=jackson
      - POSTGRES_PASSWORD=portable20relaydb!
      - POSTGRES_DB=pg_db
    networks:
      - traefik-public
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-file: "3"
        max-size: "250m"

  adminer:
    image: adminer
    ports:
      - 8088:8081
    networks:
      - traefik-public
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    depends_on: 
      - db
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        traefik.http.routers.pgadmin.entrypoints: web
        traefik.http.routers.pgadmin.rule: Host(`pgadmin.bankjsy.giize.com`)
        traefik.http.services.pgadmin.loadbalancer.server.port: 8081

networks:
  traefik-public:
    name: traefik-public
    external: true

volumes:
  postgres_data: